title: Reza's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "RezaGhari.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: MohammadReza Ghari # add your name
author-img: me.jpg # add your photo
about-author: I am a Data Science Self-learner. Always hungry to keep learning. # add description
social-twitter: RezaGhari2 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: RezaGhari # add your Github handle
social-linkedin: RezaGhari # add your Linkedin handle
social-email: Reza.Ghari@yahoo.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
